import "./globals.css";
import "./globals.scss";
import Layout from "@/components/Layout";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className="bg-backgroundbkLight">
        <Layout>
  
      
      {children}
      
      </Layout>
      </body>
    </html>
  );
}
